#!/usr/bin/env python3
"""
Build library/assets/gloss/en.*.json — deep scriptural-etymological definitions,
one per stem, generated by local Ollama against the $define spec.

Reader fallback chain:
  lexstudies (non-placeholder) -> shared gloss (this file) -> Donaldson -> hide card

Hard constraints:
  - No internet. Only Ollama + repo-local facts (morphology, Donaldson, corpus matches).
  - Throttled to <=2 physical cores and <=8 GB RAM (25% of an 8-core / 32 GB machine).
  - Resumable; priority by stem frequency; sharded output by first letter.

Run:
  python3 lds_pipeline/build_shared_gloss.py --smoke          # 10 priority stems
  python3 lds_pipeline/build_shared_gloss.py --limit 20       # smoke-test 20
  python3 lds_pipeline/build_shared_gloss.py                  # full run
  python3 lds_pipeline/build_shared_gloss.py --model gemma4:e4b
  python3 lds_pipeline/build_shared_gloss.py --force          # rebuild from scratch

Ollama must be running locally. Start with: ollama serve &
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import random
import re
import signal
import sys
import time
import unicodedata
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
CHAPTERS = REPO / "library" / "chapters"
DONALDSON = REPO / "library" / "donaldson"
GLOSS_DIR = REPO / "library" / "assets" / "gloss"
TOC_PATH = REPO / "library" / "toc.json"
LOG_PATH = REPO / "diagnostics" / "gloss-build.log"

OLLAMA_URL = "http://127.0.0.1:11434/api/generate"
OLLAMA_TAGS = "http://127.0.0.1:11434/api/tags"
OLLAMA_TIMEOUT_S = 600  # deep prompts can take a while under throttle

PROMPT_VERSION = "gloss-define-v1"

# Throttle defaults — 25% of an 8-core / 32 GB box.
NUM_THREAD = 2
NUM_CTX = 4096
NUM_PREDICT = 2500
TEMPERATURE = 0.2
JITTER_MIN_S = 2.0
JITTER_MAX_S = 3.0
WATCHDOG_EVERY = 10            # stems between watchdog checks
WATCHDOG_RSS_GB = 8.0          # soft cap; pause if exceeded
WATCHDOG_SLEEP_S = 60

# Model preference (auto-detect). Prefer strongest that fits <=8 GB RAM.
MODEL_PREFERENCE = [
    "qwen3.5:9b",
    "gemma4:e4b",
    "gemma4:latest",
    "gemma4:e2b",
    "qwen3:1.7b",
]

# Shared stop word mirroring reader + build_lex_studies.py.
_LEX = importlib.util.spec_from_file_location(
    "lex", REPO / "lds_pipeline" / "build_lex_studies.py"
)
_LEX_MOD = importlib.util.module_from_spec(_LEX)
assert _LEX.loader
_LEX.loader.exec_module(_LEX_MOD)
STOPS = _LEX_MOD.STOPS
GRAPH_STOPS = _LEX_MOD.GRAPH_STOPS

# Import morphology helpers (cached lazily inside the module).
sys.path.insert(0, str(REPO / "lds_pipeline"))
import morphology_align as morph  # noqa: E402

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
def log(msg: str) -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    line = f"[{stamp}] {msg}"
    print(line, flush=True)
    try:
        with LOG_PATH.open("a", encoding="utf-8") as fh:
            fh.write(line + "\n")
    except OSError:
        pass


# -----------------------------------------------------------------------------
# Ollama helpers
# -----------------------------------------------------------------------------
def ollama_up() -> bool:
    try:
        req = urllib.request.Request(OLLAMA_TAGS, method="GET")
        with urllib.request.urlopen(req, timeout=3) as resp:
            data = json.loads(resp.read())
        return bool(data.get("models") is not None)
    except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError):
        return False


def installed_models() -> list[str]:
    """Read manifests dir; fallback to /api/tags if server is up."""
    mdir = Path.home() / ".ollama" / "models" / "manifests" / "registry.ollama.ai" / "library"
    names: list[str] = []
    if mdir.exists():
        for family in sorted(mdir.iterdir()):
            if family.is_dir():
                for tag in sorted(family.iterdir()):
                    if tag.is_file():
                        names.append(f"{family.name}:{tag.name}")
    if not names and ollama_up():
        try:
            with urllib.request.urlopen(OLLAMA_TAGS, timeout=3) as resp:
                data = json.loads(resp.read())
            names = [m.get("name", "") for m in data.get("models", []) if m.get("name")]
        except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError):
            pass
    return names


def pick_model(requested: str | None) -> str | None:
    have = set(installed_models())
    if requested and requested in have:
        return requested
    for cand in MODEL_PREFERENCE:
        if cand in have:
            return cand
    return None


# -----------------------------------------------------------------------------
# Canon order + stem universe
# -----------------------------------------------------------------------------
def canon_chapter_order() -> list[str]:
    """Return chapter slugs in canonical order from toc.json."""
    try:
        toc = json.loads(TOC_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return sorted(p.stem for p in CHAPTERS.glob("*.html") if p.stem != "index")
    order: list[str] = []
    for item in toc:
        if not isinstance(item, dict):
            continue
        if item.get("type") == "chapter" and item.get("id"):
            order.append(item["id"])
    if not order:
        order = sorted(p.stem for p in CHAPTERS.glob("*.html") if p.stem != "index")
    return order


def load_words(path: Path) -> dict[str, Any]:
    try:
        root = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if isinstance(root, dict) and "_m" in root and "v" in root:
        catalog = root.get("_m") or []
        verses_raw = root.get("v") or {}
        out: dict[str, Any] = {}
        for vk, vdata in verses_raw.items():
            inner: dict[str, Any] = {}
            for stem, entry in (vdata or {}).items():
                e = dict(entry)
                if "matches" not in e and e.get("m"):
                    e["matches"] = [catalog[i] for i in e["m"] if 0 <= i < len(catalog)]
                inner[stem] = e
            out[vk] = inner
        return out
    return root


def is_stopword(stem: str) -> bool:
    s = (stem or "").lower()
    if not s or len(s) < 2:
        return True
    if s in STOPS or s in GRAPH_STOPS:
        return True
    # Pure numerics / short tokens are not useful headwords.
    if s.isdigit():
        return True
    return False


def gather_stem_universe() -> list[dict[str, Any]]:
    """
    Walk chapter _words.json files in canonical order, aggregate per-stem info.

    Returns a list of stem records sorted by descending appearance count so
    highest-impact stems are processed first.
    """
    order = canon_chapter_order()
    order_set = set(order)
    for p in CHAPTERS.glob("*_words.json"):
        stem_id = p.stem[: -len("_words")]
        if stem_id not in order_set:
            order.append(stem_id)

    records: dict[str, dict[str, Any]] = {}
    for slug in order:
        wpath = CHAPTERS / f"{slug}_words.json"
        if not wpath.exists():
            continue
        words = load_words(wpath)
        if not isinstance(words, dict):
            continue
        try:
            ch_num = int(slug.rsplit("_", 1)[-1])
        except ValueError:
            ch_num = 0
        for vk, vdata in words.items():
            if not str(vk).isdigit() or not isinstance(vdata, dict):
                continue
            vnum = int(vk)
            for stem, entry in vdata.items():
                if is_stopword(stem):
                    continue
                rec = records.get(stem)
                if rec is None:
                    rec = {
                        "stem": stem,
                        "count": 0,
                        "score_sum": 0.0,
                        "forms": {},
                        "first_slug": slug,
                        "first_ch": ch_num,
                        "first_v": vnum,
                        "volumes": {},
                        "examples": [],
                    }
                    records[stem] = rec
                rec["count"] += 1
                try:
                    rec["score_sum"] += float(entry.get("score") or 0)
                except (TypeError, ValueError):
                    pass
                for f in entry.get("forms") or []:
                    if not f:
                        continue
                    rec["forms"][f] = rec["forms"].get(f, 0) + 1
                vol = morph.slug_volume(slug)
                rec["volumes"][vol] = rec["volumes"].get(vol, 0) + 1
                # Collect a small pool of representative excerpts (one per stem appearance,
                # capped). We'll prune to the best 3 during fact assembly.
                if len(rec["examples"]) < 12:
                    for m in (entry.get("matches") or [])[:1]:
                        lb = (m.get("lb") or "").strip()
                        x = (m.get("x") or "").strip()
                        if lb and x:
                            rec["examples"].append({"ref": lb, "text": x, "slug": slug, "v": vnum})
                            break

    ranked = list(records.values())
    ranked.sort(key=lambda r: (-r["count"], -r["score_sum"], r["stem"]))
    return ranked


# -----------------------------------------------------------------------------
# Fact assembly
# -----------------------------------------------------------------------------
def _dominant_volume(rec: dict[str, Any]) -> str:
    vols = rec.get("volumes") or {}
    if not vols:
        return "other"
    # Prefer ot/nt/bofm where the stem actually lives.
    return max(vols.items(), key=lambda kv: kv[1])[0]


def _display_form(rec: dict[str, Any]) -> str:
    forms = rec.get("forms") or {}
    if not forms:
        return rec["stem"].capitalize()
    best = max(forms.items(), key=lambda kv: kv[1])[0]
    return best[:1].upper() + best[1:] if len(best) > 1 else best.upper()


def _pick_examples(rec: dict[str, Any], n: int = 3) -> list[dict[str, str]]:
    """Prefer spread across volumes; truncate each."""
    pool = rec.get("examples") or []
    seen_vol: set[str] = set()
    picked: list[dict[str, str]] = []
    for ex in pool:
        vol = morph.slug_volume(ex.get("slug", ""))
        if vol in seen_vol:
            continue
        picked.append(ex)
        seen_vol.add(vol)
        if len(picked) >= n:
            break
    if len(picked) < n:
        for ex in pool:
            if ex not in picked:
                picked.append(ex)
            if len(picked) >= n:
                break
    out = []
    for ex in picked[:n]:
        t = re.sub(r"\s+", " ", ex.get("text") or "")[:280].strip()
        if t and ex.get("ref"):
            out.append({"ref": ex["ref"], "text": t})
    return out


def _first_appearance_label(rec: dict[str, Any]) -> str:
    slug = rec.get("first_slug") or ""
    v = rec.get("first_v") or 0
    if not slug:
        return ""
    book = morph.book_title_from_slug(slug)
    ch = rec.get("first_ch") or 0
    return f"{book} {ch}:{v}" if ch else book


def _donaldson_hint(rec: dict[str, Any]) -> str:
    """If Donaldson has a word-study row whose headword matches this stem, return the plain/meaning text."""
    slug = rec.get("first_slug") or ""
    v = rec.get("first_v") or 0
    if not slug or not v:
        return ""
    path = DONALDSON / f"{slug}.json"
    if not path.exists():
        return ""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return ""
    block = data.get(str(v)) or {}
    forms = {f.lower() for f in (rec.get("forms") or {})}
    forms.add(rec["stem"].lower())
    best = ""
    for w in (block.get("words") or []):
        lab = (w.get("word") or "").strip().lower()
        if not lab:
            continue
        if any(lab.startswith(f) or f.startswith(lab) for f in forms):
            note = (w.get("plain") or w.get("meaning") or "").strip()
            if note and len(note) > len(best):
                best = note
    return re.sub(r"\s+", " ", best)[:600]


def _morph_bundle(rec: dict[str, Any]) -> dict[str, Any]:
    """Try to align the stem to an original-language lemma via its first appearance."""
    slug = rec.get("first_slug") or ""
    ch = rec.get("first_ch") or 0
    v = rec.get("first_v") or 0
    vol = _dominant_volume(rec)
    surface = _display_form(rec)
    nt_toks: list[dict[str, Any]] = []
    ot_toks: list[dict[str, Any]] = []
    try:
        if vol == "nt":
            nt_toks = morph.nt_tokens_for_verse(morph.book_title_from_slug(slug), ch, v)
        elif vol == "ot":
            ot_toks = morph.ot_tokens_for_verse(slug, ch, v)
    except Exception:  # morphology data may be missing
        pass
    bundle = None
    try:
        bundle = morph.align_stem(vol, rec["stem"], surface, nt_toks, ot_toks)
    except Exception:
        bundle = None
    if bundle is None:
        bundle = morph.english_only_bundle(vol, rec["stem"], surface)
    return bundle


# -----------------------------------------------------------------------------
# Prompt + output parsing
# -----------------------------------------------------------------------------
DEFINE_SYSTEM = (
    "You perform a deep scriptural-etymological analysis, not a quick definition. "
    "Begin with the original Hebrew or Greek term, transliteration, root letters, morphology, "
    "literal meaning, and semantic range. Trace the first appearance in scripture and why it matters. "
    "Trace major uses across covenant, priesthood, kingship, temple, sacrifice, creation, exodus, "
    "inheritance, judgment, exile, redemption, resurrection, and Zion contexts. Note embedded structures: "
    "repeated phrases, root echoes, paired terms, covenant patterns, symbolic oppositions, and numerical "
    "or letter patterns. Distinguish lexical certainty, strong textual pattern, plausible symbolic "
    "inference, and speculation. Do not force connections. Prefer primary texts and repeated scriptural "
    "architecture over later commentary. Close by showing what the word reveals about the wisdom, "
    "character, mission, or pattern of Jesus Christ. "
    "Respond with ONE JSON object, fenced in a ```json block, containing exactly these keys: "
    "term, language, root, literal_sense, semantic_range, first_appearance, major_scriptural_pattern, "
    "symbolic_structure, numerical_letter_observations, messianic_fulfillment, reveals_about_christ, "
    "confidence_by_claim, final_synthesis. "
    "All string values must be plain English ASCII (no Hebrew/Greek script; transliterations only). "
    "confidence_by_claim is an object mapping short claim labels to one of: "
    "'lexical', 'pattern', 'inference', 'speculation'. "
    "Write complete prose paragraphs in each field. No bullet lists. No filler."
)

REQUIRED_KEYS = {
    "term", "language", "root", "literal_sense", "semantic_range",
    "first_appearance", "major_scriptural_pattern", "symbolic_structure",
    "numerical_letter_observations", "messianic_fulfillment", "reveals_about_christ",
    "confidence_by_claim", "final_synthesis",
}
CONF_VALUES = {"lexical", "pattern", "inference", "speculation"}


def _build_user_prompt(rec: dict[str, Any], bundle: dict[str, Any],
                       examples: list[dict[str, str]], dona_hint: str) -> str:
    first = _first_appearance_label(rec)
    lang_label = {
        "grc": "Greek (New Testament)",
        "hbo": "Hebrew (Old Testament)",
        "eng": "English (Restoration volume / no original-language alignment)",
    }.get(bundle.get("lang", ""), "English")
    volumes = rec.get("volumes") or {}
    vol_label = ", ".join(f"{k}:{v}" for k, v in sorted(volumes.items(), key=lambda kv: -kv[1]))
    lines = [
        "Facts (do not invent beyond these; use them to ground the analysis):",
        f"- English stem: {rec['stem']}",
        f"- Representative surface form in the text: {_display_form(rec)}",
        f"- Language class: {lang_label}",
        f"- Lemma (if aligned): {bundle.get('lemma') or '(none)'}",
        f"- Greek surface (if any): {bundle.get('surface_gr') or ''}",
        f"- Hebrew surface (if any): {bundle.get('surface_he') or ''}",
        f"- Morphology tag (if any): {bundle.get('morph') or ''}",
        f"- Alignment confidence: {bundle.get('confidence') or 'none'}",
        f"- Appearance count across canon: {rec.get('count', 0)} verses",
        f"- Volume distribution (most to least): {vol_label}",
        f"- Earliest canonical appearance: {first or '(unknown)'}",
    ]
    if dona_hint:
        lines += ["- Donaldson word-study note (paraphrase; do not quote):", f"  * {dona_hint}"]
    if examples:
        lines.append("- Representative scripture excerpts:")
        for ex in examples:
            lines.append(f"  * {ex['ref']}: {ex['text']}")
    lines.append(
        "Return the JSON object now. Write full paragraphs in every field. "
        "If something is genuinely unknown, say so plainly in that field and mark the "
        "relevant claim as 'speculation' in confidence_by_claim."
    )
    return "\n".join(lines)


_FENCE_JSON_RE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL | re.IGNORECASE)
_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)


def _extract_json(text: str) -> dict[str, Any] | None:
    if not text:
        return None
    text = _THINK_RE.sub("", text).strip()
    m = _FENCE_JSON_RE.search(text)
    raw = m.group(1) if m else None
    if raw is None:
        # Best-effort: take the largest balanced {...} block.
        depth = 0
        start = -1
        best = None
        for i, c in enumerate(text):
            if c == "{":
                if depth == 0:
                    start = i
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0 and start >= 0:
                    cand = text[start:i + 1]
                    if best is None or len(cand) > len(best):
                        best = cand
        raw = best
    if not raw:
        return None
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Remove trailing commas as a last resort.
        cleaned = re.sub(r",(\s*[}\]])", r"\1", raw)
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError:
            return None


def _ascii_only(s: str) -> str:
    t = (s or "").replace("\u2026", "...").replace("\u2013", "-").replace("\u2014", "-")
    t = t.replace("\u201c", '"').replace("\u201d", '"').replace("\u2018", "'").replace("\u2019", "'")
    t = unicodedata.normalize("NFKD", t)
    return t.encode("ascii", "ignore").decode("ascii")


def _normalize_entry(obj: dict[str, Any]) -> dict[str, Any] | None:
    if not isinstance(obj, dict):
        return None
    missing = REQUIRED_KEYS - set(obj.keys())
    if missing:
        return None
    out: dict[str, Any] = {}
    for k in REQUIRED_KEYS:
        v = obj[k]
        if k == "confidence_by_claim":
            if not isinstance(v, dict) or not v:
                return None
            conf: dict[str, str] = {}
            for ck, cv in v.items():
                label = _ascii_only(str(ck)).strip()[:60]
                val = _ascii_only(str(cv)).strip().lower()
                if val not in CONF_VALUES:
                    # Map common stand-ins.
                    if val in {"certain", "strong"}:
                        val = "lexical"
                    elif val in {"likely", "probable"}:
                        val = "pattern"
                    elif val in {"possible", "suggestive"}:
                        val = "inference"
                    else:
                        val = "speculation"
                if label:
                    conf[label] = val
            if not conf:
                return None
            out[k] = conf
        else:
            s = _ascii_only(str(v)).strip()
            if not s or len(s) < 3:
                return None
            out[k] = s
    return out


def _validate(obj: dict[str, Any]) -> tuple[dict[str, Any] | None, str]:
    entry = _normalize_entry(obj)
    if entry is None:
        return None, "missing-keys-or-empty-values"
    # Quality floor: the analytical fields should have some real prose.
    for field in ("literal_sense", "semantic_range", "major_scriptural_pattern",
                  "reveals_about_christ", "final_synthesis"):
        if len(entry[field]) < 40:
            return None, f"field-too-short:{field}"
    return entry, ""


# -----------------------------------------------------------------------------
# Ollama request
# -----------------------------------------------------------------------------
def ollama_generate(model: str, system: str, user: str) -> str:
    payload = json.dumps({
        "model": model,
        "prompt": f"{system}\n\n{user}",
        "stream": False,
        "options": {
            "temperature": TEMPERATURE,
            "num_thread": NUM_THREAD,
            "num_ctx": NUM_CTX,
            "num_predict": NUM_PREDICT,
        },
    }).encode()
    req = urllib.request.Request(
        OLLAMA_URL, data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=OLLAMA_TIMEOUT_S) as resp:
        data = json.loads(resp.read())
    return (data.get("response") or "").strip()


def _repair_prompt(reason: str) -> str:
    return (
        f"Your previous response was rejected ({reason}). "
        "Return ONE JSON object fenced in ```json ...``` with ALL required keys: "
        "term, language, root, literal_sense, semantic_range, first_appearance, "
        "major_scriptural_pattern, symbolic_structure, numerical_letter_observations, "
        "messianic_fulfillment, reveals_about_christ, confidence_by_claim, final_synthesis. "
        "All values plain English ASCII prose (transliterations only, no Hebrew/Greek script). "
        "confidence_by_claim is an object whose values are one of: lexical, pattern, inference, speculation. "
        "Do not apologize, do not preface — just the JSON block."
    )


def generate_entry(model: str, rec: dict[str, Any]) -> tuple[dict[str, Any] | None, str]:
    bundle = _morph_bundle(rec)
    examples = _pick_examples(rec, n=3)
    dona = _donaldson_hint(rec)
    user = _build_user_prompt(rec, bundle, examples, dona)
    try:
        raw = ollama_generate(model, DEFINE_SYSTEM, user)
    except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError) as e:
        return None, f"ollama-error:{type(e).__name__}"
    obj = _extract_json(raw)
    if obj is None:
        repair_user = user + "\n\n" + _repair_prompt("could not parse JSON from the response")
        try:
            raw2 = ollama_generate(model, DEFINE_SYSTEM, repair_user)
        except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError) as e:
            return None, f"ollama-error-retry:{type(e).__name__}"
        obj = _extract_json(raw2)
        if obj is None:
            return None, "json-parse-failed"
    entry, reason = _validate(obj)
    if entry is None:
        repair_user = user + "\n\n" + _repair_prompt(reason)
        try:
            raw3 = ollama_generate(model, DEFINE_SYSTEM, repair_user)
        except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError) as e:
            return None, f"ollama-error-retry:{type(e).__name__}"
        obj2 = _extract_json(raw3)
        if obj2 is None:
            return None, "json-parse-failed-retry"
        entry, reason = _validate(obj2)
        if entry is None:
            return None, f"validation-failed:{reason}"
    # Augment with grounding facts so the reader can show chips even if the model omitted them.
    entry["_facts"] = {
        "stem": rec["stem"],
        "surface": _display_form(rec),
        "lang": bundle.get("lang") or "",
        "lemma": bundle.get("lemma") or "",
        "surface_gr": bundle.get("surface_gr") or "",
        "surface_he": bundle.get("surface_he") or "",
        "morph": bundle.get("morph") or "",
        "count": rec.get("count", 0),
        "first_appearance_ref": _first_appearance_label(rec),
    }
    return entry, ""


# -----------------------------------------------------------------------------
# Sharded IO
# -----------------------------------------------------------------------------
def shard_key_for(stem: str) -> str:
    s = (stem or "").lower()
    if not s:
        return "_other"
    c = s[0]
    if c.isalpha():
        return c
    if c.isdigit():
        return "_digits"
    return "_other"


def shard_path(key: str) -> Path:
    return GLOSS_DIR / f"en.{key}.json"


def load_shard(key: str) -> dict[str, Any]:
    p = shard_path(key)
    if not p.exists():
        return {"_meta": {"prompt_version": PROMPT_VERSION, "shard": key}, "stems": {}}
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"_meta": {"prompt_version": PROMPT_VERSION, "shard": key}, "stems": {}}
    data.setdefault("_meta", {"prompt_version": PROMPT_VERSION, "shard": key})
    data.setdefault("stems", {})
    return data


def write_shard_atomic(key: str, data: dict[str, Any]) -> None:
    GLOSS_DIR.mkdir(parents=True, exist_ok=True)
    p = shard_path(key)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=0), encoding="utf-8")
    tmp.replace(p)


def rebuild_index() -> None:
    GLOSS_DIR.mkdir(parents=True, exist_ok=True)
    index = {"_meta": {"prompt_version": PROMPT_VERSION, "generated": datetime.now(timezone.utc).isoformat(timespec="seconds")},
             "byStem": {}, "byHead": {}}
    for p in sorted(GLOSS_DIR.glob("en.*.json")):
        if p.name == "en.index.json":
            continue
        key = p.stem[len("en."):]
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        for stem, entry in (data.get("stems") or {}).items():
            index["byStem"][stem] = key
            head = (entry.get("term") or "").strip().lower()
            if head:
                index["byHead"].setdefault(head, stem)
            facts = entry.get("_facts") or {}
            surf = (facts.get("surface") or "").strip().lower()
            if surf:
                index["byHead"].setdefault(surf, stem)
    (GLOSS_DIR / "en.index.json").write_text(
        json.dumps(index, ensure_ascii=False, indent=0), encoding="utf-8"
    )


# -----------------------------------------------------------------------------
# Watchdog
# -----------------------------------------------------------------------------
def watchdog_check() -> None:
    try:
        import psutil  # type: ignore
    except ImportError:
        return
    try:
        proc = psutil.Process(os.getpid())
        rss_gb = proc.memory_info().rss / (1024 ** 3)
        load1 = os.getloadavg()[0]
        if rss_gb > WATCHDOG_RSS_GB or load1 > (os.cpu_count() or 4) * 0.5:
            log(f"watchdog: rss={rss_gb:.1f}gb load1={load1:.1f} — sleeping {WATCHDOG_SLEEP_S}s")
            time.sleep(WATCHDOG_SLEEP_S)
    except Exception:
        pass


# -----------------------------------------------------------------------------
# Main runner
# -----------------------------------------------------------------------------
_STOP = {"flag": False}


def _install_signals() -> None:
    def _handler(signum, frame):  # noqa: ARG001
        _STOP["flag"] = True
        log(f"signal {signum} — finishing current stem, then stopping")
    for s in (signal.SIGINT, signal.SIGTERM):
        try:
            signal.signal(s, _handler)
        except (ValueError, OSError):
            pass


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--model", help="Ollama model tag; auto-detect if absent")
    ap.add_argument("--limit", type=int, default=0, help="Process at most N stems (priority order)")
    ap.add_argument("--smoke", action="store_true", help="Alias for --limit 10")
    ap.add_argument("--stems", nargs="*", help="Explicit stems to process (skips priority ordering)")
    ap.add_argument("--force", action="store_true", help="Rebuild even if already in shard")
    ap.add_argument("--skip-watchdog", action="store_true")
    ap.add_argument("--dry-run", action="store_true", help="Print work plan; no Ollama calls")
    args = ap.parse_args()

    _install_signals()

    if not ollama_up():
        log("ollama not reachable at 127.0.0.1:11434. Start with: ollama serve &")
        return 2

    model = pick_model(args.model)
    if not model:
        log("no suitable model installed. Want one of: " + ", ".join(MODEL_PREFERENCE))
        return 2
    log(f"model: {model}")

    os.environ.setdefault("OLLAMA_NUM_PARALLEL", "1")
    os.environ.setdefault("OLLAMA_MAX_LOADED_MODELS", "1")

    universe = gather_stem_universe()
    log(f"universe: {len(universe)} candidate stems after stopword filtering")

    if args.stems:
        wanted = {s.lower() for s in args.stems}
        work = [r for r in universe if r["stem"].lower() in wanted]
    else:
        work = list(universe)

    limit = 10 if args.smoke else args.limit
    if limit and limit > 0:
        work = work[:limit]

    if args.dry_run:
        for rec in work[:25]:
            log(f"  plan: {rec['stem']:20s} count={rec['count']:4d} first={_first_appearance_label(rec)}")
        log(f"dry-run: {len(work)} stems would be processed")
        return 0

    # Load existing shards lazily; keep in-memory working copies.
    shards: dict[str, dict[str, Any]] = {}

    def _shard(key: str) -> dict[str, Any]:
        if key not in shards:
            shards[key] = load_shard(key)
        return shards[key]

    done = 0
    skipped = 0
    failed = 0
    dirty_keys: set[str] = set()
    FLUSH_EVERY = 5

    start = time.time()
    for i, rec in enumerate(work):
        if _STOP["flag"]:
            break
        stem = rec["stem"]
        key = shard_key_for(stem)
        sh = _shard(key)
        if (not args.force) and stem in sh["stems"]:
            skipped += 1
            continue
        if not args.skip_watchdog and i > 0 and i % WATCHDOG_EVERY == 0:
            watchdog_check()

        t0 = time.time()
        entry, reason = generate_entry(model, rec)
        elapsed = time.time() - t0
        if entry is None:
            failed += 1
            log(f"  fail {stem:20s} reason={reason} ({elapsed:.1f}s)")
        else:
            sh["stems"][stem] = entry
            sh["_meta"]["model"] = model
            sh["_meta"]["prompt_version"] = PROMPT_VERSION
            sh["_meta"]["updated"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
            dirty_keys.add(key)
            done += 1
            log(f"  ok   {stem:20s} count={rec['count']:4d} first={_first_appearance_label(rec)} ({elapsed:.1f}s)")

        if dirty_keys and (done % FLUSH_EVERY == 0 or _STOP["flag"]):
            for k in list(dirty_keys):
                write_shard_atomic(k, shards[k])
            dirty_keys.clear()
            rebuild_index()

        # Jitter to avoid back-to-back generations with no gap.
        time.sleep(random.uniform(JITTER_MIN_S, JITTER_MAX_S))

    # Final flush.
    if dirty_keys:
        for k in list(dirty_keys):
            write_shard_atomic(k, shards[k])
        rebuild_index()
    else:
        # Still refresh the index so additions (e.g. via --stems) are discoverable.
        rebuild_index()

    wall = time.time() - start
    log(f"done: wrote={done} skipped={skipped} failed={failed} wall={wall:.0f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
